default_settings: null
behaviors:
  My Behavior:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 0.001
      beta: 0.001
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 3
      vis_encode_type: simple
      memory: null
      goal_conditioning_type: hyper
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
        network_settings:
          normalize: false
          hidden_units: 128
          num_layers: 2
          vis_encode_type: simple
          memory: null
          goal_conditioning_type: hyper
    init_path: null
    keep_checkpoints: 50
    checkpoint_interval: 500000
    max_steps: 10000000
    time_horizon: 128
    summary_freq: 10000
    threaded: false
    self_play: null
    behavioral_cloning: null
env_settings:
  env_path: C:\Users\Park woojin\Desktop\2021_RLKR_Drone_Delivery_Challenge_with_Unity-master\DroneDelivery.exe
  env_args: null
  base_port: 5005
  num_envs: 1
  seed: -1
engine_settings:
  width: 1080
  height: 720
  quality_level: 5
  time_scale: 50.0
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: false
environment_parameters: null
checkpoint_settings:
  run_id: Day7_Drone_pnltoen(PPO)_Buffer_learningrate_hidden_unit_normalize
  initialize_from: null
  load_model: false
  resume: false
  force: true
  train_model: false
  inference: false
  results_dir: results
torch_settings:
  device: null
debug: false
