default_settings: null
behaviors:
  My Behavior:
    trainer_type: ppo
    hyperparameters:
      batch_size: 128
      buffer_size: 5120
      learning_rate: 0.0002
      beta: 0.005
      epsilon: 0.2
      lambd: 0.999
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 3
      vis_encode_type: simple
      memory: null
      goal_conditioning_type: hyper
    reward_signals:
      extrinsic:
        gamma: 0.999
        strength: 1.0
        network_settings:
          normalize: false
          hidden_units: 128
          num_layers: 2
          vis_encode_type: simple
          memory: null
          goal_conditioning_type: hyper
    init_path: null
    keep_checkpoints: 150
    checkpoint_interval: 500000
    max_steps: 30000000
    time_horizon: 32
    summary_freq: 10000
    threaded: false
    self_play: null
    behavioral_cloning: null
env_settings:
  env_path: C:\Users\Park woojin\Desktop\2021_RLKR_Drone_Delivery_Challenge_with_Unity-master\DroneDelivery.exe
  env_args: null
  base_port: 5005
  num_envs: 1
  seed: -1
engine_settings:
  width: 576
  height: 372
  quality_level: 5
  time_scale: 20
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: false
environment_parameters: null
checkpoint_settings:
  run_id: reward_1_0_0.1
  initialize_from: null
  load_model: false
  resume: false
  force: true
  train_model: false
  inference: false
  results_dir: results
torch_settings:
  device: null
debug: false
